stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/MachineLearningRating_v3.txt
    outs:
      - data/processed/cleaned_data.csv
      - data/processed/cleaned_data_sample.csv

  eda:
    cmd: python src/eda.py
    deps:
      - src/eda.py
      - data/processed/cleaned_data_sample.csv
    outs:
      - results/eda_report.html
